# docker stack deploy -c docker-compose.yml <stack name>
version: '3.5'

services:

  sandman-dns-manager:
    image: abilioesteves/sandman-dns-webhook-hook-sample:0.0.6
    ports: 
      - 7070:7070

  sandman-dns-listener:
    image: abilioesteves/sandman-swarm-listener:0.0.6
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.38
      - SANDMAN_DNS_MANAGER_ADDRESS=sandman-dns-manager:7070
      - SANDMAN_REVERSE_PROXY_ADDRESS=0.0.0.0
      - SANDMAN_DNS_TAGS=internal,intranet,internet
